### ISSUE TITLE
สระยังมีปัญหาครับ ตามนี้เลย

### ISSUE THREAD

**Issue by karorogunso** [lion328/ThaiFixes#2]
http://puu.sh/eXo1p/6307040854.png << full ss
http://puu.sh/eXnVX/199b448fc9.png < Small ss

Hey Check this out :D
MCClient 1.7.10+Forge with Tabby Chat 1.11.22 (1.11.2.2)

Keep do a good work :dango: :tea: 

Nom Nom Nom
# karorogunso

**Comment by lion328** [comment]
ขอบคุณที่แจ้งมาครับ ทางเราก็มีปัญหานี้อยู่เหมือนกัน
