### ISSUE TITLE
Minecraft 1.13

### ISSUE THREAD

**Issue by riflowth** [lion328/ThaiFixes#35]
I'm waiting for this mod to support Minecraft version 1.13. I hope you release this mod in soon 😃

**Comment by lion328** [comment]
I need to wait for MinecraftForge 1.13 (or another APIs that can be used, e.g., LiteLoader) to develop. I probably need to rewrite many parts of the mod though, so this can take longer time.

**Comment by lion328** [comment]
Closed. Discussion are moved to #36.
