### ISSUE TITLE
Planning for Minecraft 1.13

### ISSUE THREAD

**Issue by lion328** [lion328/ThaiFixes#36]
Since Minecraft 1.13 was released now, it comes with major rewritten of many parts of the game including font rendering-related part. This means we might need to rewrite the mod, probably the entire thing.

I heard there is a discussion about MinecraftForge coremod restriction in Minecraft 1.13, so I think we should drop the coremod section.

Minecraft 1.13 is using Java 8, so we can upgrade ThaiFixes to Java 8 too.

The question is what approach should we do? I actually want to do coremod thing since its will compatible with a lot of mods, including mods that messing with font system, but as I stated above, there are restrictions.

TBH, i want to use LiteLoader because their Mixins is powerful in manageable way, but I will use what going to come out first.

**Comment by lion328** [comment]
Someone told me that there's a new mod API for Minecraft 1.13 called [Rift](https://github.com/DimensionalDevelopment/Rift). Although its lacks of decent documentation, I might use it anyway since probably not hard to figure it out, and most important, they have support for coremods and Mixin.

**Comment by ruyi3** [comment]
^ ู^

**Comment by lion328** [comment]
We proceeded to go with Rift for now.

**Comment by kowith337** [comment]
FYI: http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.13.2.html
Releases since 2019/02/15, latest update yesterday, but...
- homepage still recommended 1.12.2 by default
- no recommended version for 1.13.2 yet
- need to access that version manually

**Comment by lion328** [comment]
Thanks @kowith337. I should make it clear that I feel like lost interest in this project, so you can check out a "better" maintained fork [here](https://github.com/secretdataz/ThaiFixes-Fabric) that supported 1.13 and 1.14 snapshots. It uses Fabric though. I will update README later.

I don't see a point why ThaiFixes going to use Forge again. Mixins approach seems to be better overall, probably easier too (for this mod).
