### ISSUE TITLE
Incompatible with Forge 14.23.4.2764

### ISSUE THREAD

**Issue by SteveKunG** [lion328/ThaiFixes#38]
Caused by https://github.com/MinecraftForge/MinecraftForge/pull/5159

Log :
https://pastebin.com/Rw2JZ5jj

![2018-09-28_12 57 24](https://user-images.githubusercontent.com/6128413/46190549-362aa600-c31e-11e8-8333-9a1bb9674c01.png)

**Comment by willywotz** [comment]
same

**Comment by lion328** [comment]
Please retest with [4.8.1-1.12.2](https://github.com/lion328/ThaiFixes/releases/tag/4.8.1-1.12.2).

**Comment by willywotz** [comment]
> Please retest with [4.8.1-1.12.2](https://github.com/lion328/ThaiFixes/releases/tag/4.8.1-1.12.2).

have new bug https://pastebin.com/mdzcQ5Sm

**Comment by lion328** [comment]
@willywotz Thanks for your testing. Can you retest again with only ThaiFixes?

**Comment by willywotz** [comment]
new report https://pastebin.com/vP95bJ2j

**Comment by lion328** [comment]
@willywotz Can you post the full log? Thanks.

**Comment by willywotz** [comment]
this file ? (/logs/latest): https://pastebin.com/tSfBcSwz

**Comment by lion328** [comment]
Okay, so I analyzed the compile binaries of 4.8 and 4.8.1, and I found that the method name of `I18n.format` in each binaries are different. SRG name of the method is using in 4.8, but not in 4.8.1 since it using unobfuscated name. Still doesn't explain why it is working on my side but not yours, maybe configs are different or something.

**Comment by lion328** [comment]
@willywotz [Can you try this one?](https://github.com/lion328/ThaiFixes/releases/download/4.8.1-1.12.2/thaifixes-4.8.1R-1.12.2.jar) I recompiled with reobf, and it produced obfuscated name as in previous releases.

**Comment by willywotz** [comment]
> @willywotz [Can you try this one?](https://github.com/lion328/ThaiFixes/releases/download/4.8.1-1.12.2/thaifixes-4.8.1R-1.12.2.jar) I recompiled with reobf, and it produced obfuscated name as in previous releases.

it's worked thanks.
