### ISSUE TITLE
สระซ้อนกัน เมื่อใช้ MCPX Font บน Chat , Hologram และ Title

### ISSUE THREAD

**Issue by speccycy** [lion328/ThaiFixes#39]
ThaiFixes 4.8.1-1.12.2

สระซ้อนกัน เมื่อใช้ MCPX Font ข้อความบน Hologram และ Title ครับ

Title
![2021-10-03_18 23 35](https://user-images.githubusercontent.com/68125477/135751692-555cd81b-c4d0-427a-a0a9-c43e77de2800.png)

Chat
![image](https://user-images.githubusercontent.com/68125477/135752168-77fe8412-cdfc-4444-a961-b6ce08c06d94.png)

**Comment by lion328** [comment]
สวัสดีครับ

ขอโทษด้วยนะครับที่ตอบช้า ดูจาก screenshot แล้วน่าจะมีปัญหาเฉพาะกับตัวหนาครับ พอจะ screenshot เพิ่มมาได้ไหมครับว่า font แบบ unicode ของเกมเป็นเหมือนกันไหม

ขอบคุณครับ

**Comment by speccycy** [comment]
> สวัสดีครับ
> 
> ขอโทษด้วยนะครับที่ตอบช้า ดูจาก screenshot แล้วน่าจะมีปัญหาเฉพาะกับตัวหนาครับ พอจะ screenshot เพิ่มมาได้ไหมครับว่า font แบบ unicode ของเกมเป็นเหมือนกันไหม
> 
> ขอบคุณครับ

Font แบบ Unicode ไม่เป็นครับผม
ตอนนี้ใช้แบบ Unicode อยู่ครับ

ขอบคุณที่ยังกลับมาตอบครับบ น้ำตาจิไหล ;w;
